# This is a basic workflow to help you get started with Actions
name: Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'

jobs:
  # This workflow contains a single job called "build"
  run-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies With Yarn
        run: yarn --frozen-lockfile

      - name: Jest run
        run: yarn test
